import { Product } from '@/types'

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Cire Cheveux Premium',
    slug: 'cire-cheveux-premium',
    description: 'Tenue forte, brillance naturelle. Formule premium pour un style impeccable toute la journée.',
    price: 2490,
    images: ['/images/products/cire-cheveux.jpg'],
    category: 'coiffant',
    stock: 50,
    is_dropshipping: false,
    benefit: 'Fixation forte toute la journée',
    trust: ['Fixation forte 24h', 'Effet naturel & brillance mat', 'Livraison sous 48h', 'Satisfait ou remboursé'],
    related: ['3', '4'],
    seo_title: 'Cire Cheveux Premium SP Barber — Tenue Forte & Brillance',
    seo_description: 'Cire cheveux premium pour homme. Tenue forte, brillance naturelle. Livraison rapide en France.',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Shampooing Noir Colorant',
    slug: 'shampooing-noir-colorant',
    description: 'Ravive et intensifie la couleur noire naturellement. Sans ammoniaque, sans peroxyde.',
    price: 2890,
    images: ['/images/products/shampooing-noir.jpg'],
    category: 'soin',
    stock: 40,
    is_dropshipping: false,
    benefit: 'Cheveux noirs intenses dès 1 lavage',
    trust: ['Couleur ravivée en 1 lavage', 'Sans ammoniaque ni peroxyde', 'Livraison sous 48h', 'Satisfait ou remboursé'],
    related: ['1', '4'],
    seo_title: 'Shampooing Noir Colorant SP Barber — Cheveux Noirs Intenses',
    seo_description: 'Shampooing colorant noir pour homme. Ravive naturellement la couleur. Sans ammoniaque.',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Crème Curl Control',
    slug: 'creme-curl-control',
    description: 'Définit et discipline les boucles avec légèreté. Hydratation longue durée.',
    price: 2690,
    images: ['/images/products/creme-curl.jpg'],
    category: 'coiffant',
    stock: 35,
    is_dropshipping: false,
    benefit: 'Boucles définies sans effet lourd',
    trust: ['Boucles définies & hydratées', 'Sans résidu, sans alourdissement', 'Livraison sous 48h', 'Satisfait ou remboursé'],
    related: ['2', '4'],
    seo_title: 'Crème Curl Control SP Barber — Boucles Définies',
    seo_description: 'Crème curl control pour cheveux bouclés. Définition et hydratation longue durée.',
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Peigne Texture Expert',
    slug: 'peigne-texture-expert',
    description: 'Peigne professionnel pour sculpter et texturer. Dents larges anti-casse.',
    price: 1490,
    images: ['/images/products/peigne-texture.jpg'],
    category: 'accessoire',
    stock: 80,
    is_dropshipping: false,
    benefit: 'Précision pro — dents anti-casse',
    trust: ['Dents renforcées anti-casse', 'Idéal cheveux épais & texturés', 'Livraison sous 48h', 'Satisfait ou remboursé'],
    related: ['1', '3'],
    seo_title: 'Peigne Texture Expert SP Barber — Professionnel',
    seo_description: 'Peigne texture expert pour homme. Dents larges anti-casse. Idéal pour cheveux épais.',
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Pack Barbe Complet',
    slug: 'pack-barbe-complet',
    description: 'Tout ce qu\'il faut pour une barbe parfaite : huile, baume, peigne et ciseaux.',
    price: 4990,
    images: ['/images/products/pack-barbe.jpg'],
    category: 'barbe',
    stock: 25,
    is_dropshipping: false,
    benefit: '5 essentiels barbe — économisez 35€',
    trust: ['5 produits complémentaires inclus', 'Valeur 85€ — vous économisez 35€', 'Livraison sous 48h', 'Satisfait ou remboursé'],
    related: ['1', '4'],
    seo_title: 'Pack Barbe Complet SP Barber — Kit Barbe Premium',
    seo_description: 'Pack barbe complet pour homme. Huile, baume, peigne et ciseaux. Kit barbe premium.',
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Tondeuse Fade Pro',
    slug: 'tondeuse-fade-pro',
    description: 'Tondeuse professionnelle pour des dégradés parfaits. Lames acier japonais.',
    price: 7990,
    images: ['/images/products/tondeuse-fade.jpg'],
    category: 'accessoire',
    stock: 999,
    is_dropshipping: true,
    dsers_url: 'https://www.dsers.com',
    benefit: 'Dégradé pro — lames japonaises',
    trust: ['Lames acier japonais inoxydables', 'Dégradé précis comme en salon', 'Livraison sous 48h', 'Satisfait ou remboursé'],
    related: ['4', '1'],
    variants: [
      { id: '6a', name: 'Standard — 79,90€', price: 7990, stock: 999 },
      { id: '6b', name: 'Pro — 89,90€', price: 8990, stock: 999 },
      { id: '6c', name: 'Elite — 99,90€', price: 9990, stock: 999 },
    ],
    seo_title: 'Tondeuse Fade Pro SP Barber — Dégradé Parfait',
    seo_description: 'Tondeuse professionnelle pour dégradé fade. Lames acier japonais. Livraison via DSers.',
    created_at: new Date().toISOString(),
  },
]
